#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20

script=1
while [ $script -le 20 ]
do
    echo $script
case $script in
4)
    echo "bad luck from China" ;;
9)
    echo "bad luck from Japan" ;;
17)
    echo "bad luck from Italy" ;;
esac
    ((script++))
done
